[build]
  command = "npm run build"
  publish = "dist"
  base = ""  # ✅ keep root clean, no subfolder

[dev]
  command = "npm run dev"
  port = 5173
  targetPort = 5173
  publish = "dist"
  framework = "vite"

[build.environment]
  NODE_VERSION = "18"
  VITE_API_BASE_URL = "https://eaglesoakltd-backend.onrender.com/"
