[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  VITE_API_BASE_URL = "https://api.eaglesoak.comhttps://eaglesoakltd-backend.onrender.com" # change to your actual backend URL

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
